packages:
  - '.'

allowBuilds:
  '@parcel/watcher': true
  core-js: false
  esbuild: true
  unrs-resolver: true
  vue-demi: true

overrides:
  dompurify: ^3.4.14
  nanoid: ^3.3.18
  postcss: ^8.5.23

patchedDependencies:
  '@ianvs/prettier-plugin-sort-imports': patches/@ianvs__prettier-plugin-sort-imports.patch
  prettier-plugin-organize-attributes: patches/prettier-plugin-organize-attributes.patch

peerDependencyRules:
  allowedVersions:
    eslint: '10'
